### ISSUE TITLE
一些疑问和建议

### ISSUE THREAD

**Issue by xrh0905** [SRInternet/Seewo-Custom_Start#3]
您好！首先感谢您为这个作品的付出，软件非常好用，具有很强的节目效果XD
但我还是有一些疑问和发现的问题，希望可以得到解答。

1. 为什么需要管理员权限？
2. 连续多次启动时，动画和音效会重复播放
3. 白板正常运行时启动还是会触发
4. 白板批注模式下启动还是会触发，这一行为与官启不同
5. 希沃白板更新后窗口更名为`希沃白板 5`，现在需要手动替换

针对其中的问题，我有一些建议

- 针对`EasiNote`窗口（批注模式）进行识别，批注模式直接启动主程序，复刻官启行为
- 希沃白板默认驻留后台加速启动速度，可能影响识别

您的作品仍然是目前我使用的最好的作品，再次感谢。

针对上述的问题，我尝试修改过，但是我对VB不熟。目前我用Python又套了一层使用。

**Comment by jiangyin14** [comment]
你所提出的问题，大部分都已经被3.1版本修复，3.1版本即将发布，请关注B站官方号。
关于3.1的源代码，会在晚些时候提交
