### ISSUE TITLE
如何还原官方的启动

### ISSUE THREAD

**Issue by panyt0615** [SRInternet/Seewo-Custom_Start#4]
如题，如果我想暂时用回官方的启动器，我该如何操作。
PS:我尝试了还原backup中的文件，但是它提示环境发生变化，需要重新去官网下载。
期待您的回复，同时感谢您为开发做出的努力。

**Comment by jiangyin14** [comment]
目前，启动器安装后会把原本的包放入backup目录中，你可以使用其中的所有的文件替换swenlauncher中的所有文件，暂时没有“一键恢复”的设置，我们会考虑实现这个功能。

**Comment by jiangyin14** [comment]
经过测试，提示“环境发生变化”这种情况似乎是100%复现的。
解决方案：升级到最新版

小技巧：Seewo/EasiNote5/5.2.xxxx（尾数最大）/Main/EasiNote5.exe被打开时，行为和原本的swenlauncher.exe是一致的，可以作为临时代替方案。
