### ISSUE TITLE
[Refactor Request] 请整理仓库文件

### ISSUE THREAD

**Issue by yangnuozhen** [SRInternet/Seewo-Custom_Start#5]
## 问题描述

本仓库和解决方案文件过于杂乱，几乎所有项目文件全部堆在根目录，不利于自身维护和第三方阅读。

另外Git的Commits说明不够明了，请参考Git Commit规范。

## 期望行为
重构项目文件，规范目录结构。例如把所有的图片文件放在img目录。

**Comment by yangnuozhen** [comment]
另外bin和obj文件夹不应该放置于仓库文件之中，在.gitignore 应当设置。
生成的文件应该发布于Release。

这里不是网盘。

**Comment by jiangyin14** [comment]
感谢您对我们工作规范性的等方面错误的指出，我们感激不尽。我们会找时间重构项目目录，如果可以的话，您可以加入我们的工作室交流QQ群367798007或者Telegram群siruichat，问题将会获得更有效的解决。

**Comment by jiangyin14** [comment]
感谢您的提醒，我们已经启动对目录结构的优化工作。

**Comment by LittleTiger2333** [comment]
根目录下ttf和图片应该清理，不然git同步时会全都下载下来，增加占用

**Comment by jiangyin14** [comment]
> 根目录下ttf和图片应该清理，不然git同步时会全都下载下来，增加占用

明白，我们会把引用的Assets压缩打包并提供思锐云盘高速外链以供使用

**Comment by jiangyin14** [comment]
近期工作室安排较为密集，Refactor可能推迟

**Comment by jiangyin14** [comment]
Refactor已经完毕，感谢您的支持。
@LittleTiger2333 
@yangnuozhen
